/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  id("pl.zalas.structurizr-cli") version "1.1.1"
}

repositories {
    mavenCentral()
}

val plantuml by configurations.creating
val workspace by configurations.creating
val workspacepuml by configurations.creating

dependencies {
    "plantuml"("net.sourceforge.plantuml:plantuml:1.2021.10")
    "workspace"(files("src/structurizr/workspace.dsl"))
}

structurizrCli {
    export {
        format = "plantuml"
        workspace = "src/structurizr/workspace.dsl"
    }
}
tasks.named("structurizrCliExport") { dependsOn(configurations["workspace"])}

tasks.register<Copy>("copyWorkspacePlantUML") {
    dependsOn("structurizrCliExport")
    from("src/structurizr")
    include("*.puml")
    into(layout.buildDirectory.dir("workspace"))
}

tasks.register<JavaExec>("execPlantUml") {
    dependsOn("copyWorkspacePlantUML")
    val srcFiles = "$buildDir/workspace/structurizr-*.puml"
    val outDir = "$buildDir/images"
    group = "plantuml"
    classpath = configurations["plantuml"]
    args(listOf(srcFiles, "-o", outDir, "-tsvg"))
}

tasks.register("buildImages") {
    dependsOn("execPlantUml")
}

tasks.register("build") {
    dependsOn("buildImages")
}

tasks.register<Delete>("cleanStructurizr"){
    delete(files("src/structurizr/structurizr-*.puml"))
}

tasks.register<Delete>("cleanImages"){
    delete(layout.buildDirectory.dir("images"))
}

tasks.register<Delete>("cleanWorkspace"){
    delete(layout.buildDirectory.dir("workspace"))
}
